TARGET = vecteur

CC = g++

CFLAGS = -Wall -Wextra -std=c++11

SRC = vecteur.cpp main.cpp

all: $(TARGET)

$(TARGET): $(SRC)
	$(CC) $(CFLAGS) -o $(TARGET) $(SRC)

clean:
	rm -f $(TARGET)
